### ISSUE TITLE
Todo Project Brainstorm List 

### ISSUE THREAD

**Issue by jorgehjr84** [jorgehjr84/TIY-Assignments#9]
- [ ] Do some research on how do I delete 
- [ ] Do I want the item to be deleted
- [ ] Should the list be shorter 
- [ ] I want to remove taskList[ x] ;
- [ ] May need a command saying, are these two list different now
- [ ] I want to show the task list with the removed task now
